version: '3.3'

services:
  database:
    image: "mariadb:10.3"
    container_name: "database"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Vmware1!"
      
  webapp:
    image: "webapp:latest"
    container_name: "Front-End"
    restart: always
    ports:
      - 80:80

  webapi:
    image: "webapi:latest"
    container_name: "Back-End"
    restart: always
    ports:
      - 44387:44387

networks:
    default:
        external:
            name: HexTech


